import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'inverse-surface': 'var(--color-inverse-surface)',
        tertiary: 'var(--color-tertiary)',
        'surface-variant': 'var(--color-surface-variant)',
        'surface-dim': 'var(--color-surface-dim)',
        background: 'var(--color-background)',
        'on-error': 'var(--color-on-error)',
        'surface-container': 'var(--color-surface-container)',
        'on-background': 'var(--color-on-background)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'secondary-container': 'var(--color-secondary-container)',
        'error-container': 'var(--color-error-container)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        secondary: 'var(--color-secondary)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'on-secondary': 'var(--color-on-secondary)',
        outline: 'var(--color-outline)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'outline-variant': 'var(--color-outline-variant)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'on-primary-container': 'var(--color-on-primary-container)',
        error: 'var(--color-error)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'on-primary': 'var(--color-on-primary)',
        'surface-bright': 'var(--color-surface-bright)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        surface: 'var(--color-surface)',
        primary: 'var(--color-primary)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'surface-tint': 'var(--color-surface-tint)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'on-surface': 'var(--color-on-surface)',
        'on-error-container': 'var(--color-on-error-container)',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      spacing: {
        'stack-md': '16px',
        'stack-sm': '8px',
        'container-max': '1280px',
        'margin-mobile': '20px',
        gutter: '24px',
        'stack-lg': '32px',
        'section-gap': '160px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'label-caps': ['Geist', 'sans-serif'],
        'display-lg': ['Geist', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'mono-label': ['Geist', 'sans-serif'],
        'display-lg-mobile': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '32px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
        'display-lg': ['80px', { lineHeight: '88px', letterSpacing: '-0.04em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'mono-label': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'display-lg-mobile': ['48px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};

export default config;